version: '3'

services:
  customersreportsdb:
    image: mongo
    container_name: customersreportsdb-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: customerspass
    ports:
      - "27018:27017"
  mongo-express-customersreportsdb:
    image: mongo-express
    container_name: mongo-express-customersreportsdb
    ports:
      - 8092:8081
    volumes:
      - customersreportsdb-local:/data/db

    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=customerspass
      - ME_CONFIG_MONGODB_SERVER=customersreportsdb
    depends_on:
    - customersreportsdb
    
volumes:
  customersreportsdb-local:
    driver: local
